minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # shiguredo
  - sora-js-sdk
  - "@shiguredo/*"
  # voidzero
  - "@voidzero-dev/*"
  - "@vitest/*"
  - "vite-plus"

onlyBuiltDependencies:
  - esbuild

peerDependencyRules:
  allowedVersions:
    vite: ">=0.1.0"
    vitest: ">=0.1.0"
    typescript: ">=6.0.0"
