# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

fail_fast = true
default_stages = ["pre-commit"]

[[repos]]
repo = "local"
hooks = [
  { id = "check", name = "pnpm check", entry = "pnpm run check", language = "system", pass_filenames = false, priority = 0 },
  { id = "test", name = "pnpm test", entry = "pnpm run test", language = "system", pass_filenames = false, always_run = true, priority = 20 },
]
