name: ci

on:
  push:
    branches:
      - master
      - develop
      - "feature/*"
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "releases/*"
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1.10.0
        with:
          node-version: "26"
          run-install: true
      - run: vp check
      - run: vp build
      - run: vp test run

  slack_notify:
    needs:
      - ci
    permissions:
      actions: read
    timeout-minutes: 5
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: sora-devtools
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
