name: ci

on:
  push:
    branches:
      - master
      - develop
      - "feature/*"
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "releases/*"
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "26"
      - run: vp install
      - run: vp lint --type-aware
      - run: tsc --noEmit
      - run: vp test run
      - run: vp build

  slack_notify:
    needs:
      - ci
    permissions:
      actions: read
    timeout-minutes: 5
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: sora-devtools
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
