name: e2e-test

on:
  push:
    branches:
      - develop
      - "feature/*"
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "releases/*"

jobs:
  e2e-test:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # browser: ["chromium", "firefox", "webkit"]
        browser: ["chromium"]
    env:
      E2E_TEST_SORA_SIGNALING_URL: ${{ secrets.TEST_SIGNALING_URL }}
      E2E_TEST_SORA_CHANNEL_ID_PREFIX: ${{ secrets.TEST_CHANNEL_ID_PREFIX }}
      E2E_TEST_ACCESS_TOKEN: ${{ secrets.TEST_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "26"
          cache: true
      - run: vp install
      - run: vp build
      - run: pnpm exec playwright install ${{ matrix.browser }} --with-deps
      - run: pnpm exec playwright test --project=${{ matrix.browser }}
        env:
          VITE_SORA_CHANNEL_ID_SUFFIX: _24

  slack_notify:
    needs:
      - e2e-test
    permissions:
      actions: read
    timeout-minutes: 5
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: sora-devtools
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
